config/routes.rb
Sam::Application.routes.draw do

  get "welcome/index"
  get "interactions/symposium"
  get "itenerarys/choose_city"  
  get "users/map_choice"

  get "guardians/for_parents"
  get "guardians/recent"
  get "guardians/blocked"
  get "guardians/friends"
  get "guardians/questions"
  get "guardians/answers"

  devise_for :users
  devise_for :guardians, controllers: { registrations: "guardians/registrations" }

  resources :profiles
  resources :journeys
  resources :itenerarys

  get "users/dashboard"
  get "users/history"
  get "users/search_journey"

  root 'welcome#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base

  belongs_to :user

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def create
    profile = Profile.new(religion: params[:religion],
                          user_id: current_user.id)
    if params[:city]
      current_user.city = params[:city]
      current_user.save
    end

    if profile.save
      redirect_to users_dashboard_path
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.religion = params[:religion]
    if @profile.update(params[:profile].permit(:religion))
      redirect_to users_dashboard_path
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_tag profiles_path, method: :post do %>
  <h2 class="white lobster">Profile<h2>
  <h4 class="white">Religion</h4>
  <%= text_field_tag :religion, nil, :placeholder => "jane darma" %>
  <h4 class="white">Rooms in your Home?</h4>
  <%= text_field_tag :rooms, nil, placeholder: "3"%>
  <h4 class = "inline white">City is <%=current_user.city%>?</h4>
  <%= link_to "not correct", "#", id: "correct-city"%></br>
  <%= text_field_tag :city, nil, placeholder: "Paris", class: "hide", id: "city"%>
  <%= submit_tag "Create profile", class: "button", id: "create-profile"%>
<% end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="small-4 large-4 columns">
    <%= form_for :profile, url: profile_path, method: :patch do |f| %>
      <h4>Religion</h4>
      <%= f.text_field :religion %>
      <%= f.submit "Update", class: "button"%>
    <% end %>
    <%= link_to "cancel", users_dashboard_path%>
  </div>
</div>