config/routes.rb
Sam::Application.routes.draw do

  get "welcome/index"
  get "interactions/symposium"
  get "itenerarys/choose_city"  
  get "users/map_choice"

  get "guardians/for_parents"
  get "guardians/recent"
  get "guardians/blocked"
  get "guardians/friends"
  get "guardians/questions"
  get "guardians/answers"

  devise_for :users
  devise_for :guardians, controllers: { registrations: "guardians/registrations" }

  resources :profiles
  resources :journeys
  resources :itenerarys

  get "users/dashboard"
  get "users/history"
  get "users/search_journey"

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  include Shaman

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_one :guardian
  has_many :journeys

  validates :email, :encrypted_password, presence: true

  scope :except_me, ->(user) { where.not(id: user) }

  geocoded_by :ip_address, latitude: :lat, longitude: :long

  reverse_geocoded_by :lat, :long do |obj, results|
    if geo = results.first
      obj.city = geo.city
    end
  end

  after_validation :geocode, :reverse_geocode

  #The actual User attribute current_sign_in_ip will be unchanged.
  #Geocode will inject the values of :lat and :long based off
  #of the spoofed ip when in develoopment or test enviroments.

  def ip_address
    if Rails.env == "test"
      "50.78.167.161"
    elsif Rails.env == "production"
      self.current_sign_in_ip
    end
  end

  def religion
    self.profile.religion
  end

  def last_interactions 
    journey = self.journeys.last
    itenerary = journey.itenerary
    itenerary.interactions
  end

  #returns distance from city, or lat and long to current_user
  #I'm seperating this geocode function in case a better option 
  #exist
  def range_finder destination
    self.distance_to(destination)
  end

  #returns an array of users that are 'distance' away from current_user
  def by_distance distance, operator
    array = []
    User.except_me(self).each do |user|
      user_dist = self.range_finder(user.geo)
      if user_dist.send(operator, distance) and user_dist > distance/3 
        array << user
      end
    end
    array
  end

  #returns one random user from an array of users
  def self.random array
    id_count = array.count
    array[rand(id_count)]
  end

  def geo
    [self.lat, self.long]
  end

  #returns a base user for the first interaction in a journey
  #all other interactions will be based of this interaction
  def base_interaction distance
    User.random(self.by_distance(distance, :>))
  end

  def next_interaction distance
    User.random(self.by_distance(distance, :<))
  end

  def iteneraries
    array = []
    self.journeys.each do |journ|
      array << journ.itenerary
    end
    array
  end

  def interactions 
    array = []
    self.iteneraries.each do |iten|
      array << iten.interactions
    end
    array.flatten
  end

  def interactions_users
    array = []
    self.interactions.each do |inter|
      array << inter.user
    end
    array
  end

  def distance_to_increment city1, city2
    unless $redis.get("#{city1}_#{city2}")
      distance = Geocoder::Calculations.distance_between(city1, city2).round
      $redis.set("#{city1}_#{city2}", distance)
    end
    $redis.get("#{city1}_#{city2}").to_i
  end

  #the hash key is the city. The key signifies the city x in the 
  #equation x to y in miles. It makesit easier this way to access the distances
  #by hash in the view @distance[city] because the distances will be under each 
  #city in the Itenerary show view

  def city_distance destinations
    d = destinations
    hash = {}
    count = d.count
    x, y = 0, 1
    while y < count
      hash["#{d[x]}"] = self.distance_to_increment(d[x], d[y]) 
      x += 1
      y += 1
    end
    hash
  end

  def journey_interactions_hash
    hash = {}
    self.journeys.each do |journ|
      hash[journ.name] = journ.interactions
    end
    hash
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :js, :html
  before_action :authenticate_user!
  before_action :authenticate_users_guardian
  before_action :authenticate_guardian!

  def dashboard
    @users = User.all
    unless current_user.interactions.empty?
      @hash = gmap
    end
    @map = "default_map"
  end

  def history
    unless params[:search]
      @journeys = current_user.journeys
    else
      @journeys = Journey.search(params[:search])
    end
  end

  def map_choice
    @options_hash = {map_choice: params[:map_choice], hash: gmap}
    respond_with @options_hash
  end

  def search_journey
    if params[:search]
      @journeys = Journey.search(params[:search], current_user.id)
    end
      respond_with @journeys
  end

  def parent

  end

private

  def authenticate_users_guardian
    if current_user.guardian == current_guardian
      return
    else
      sign_out current_guardian
      redirect_to new_guardian_session_path
    end
  end

  def gmap
    unless current_user.journeys.empty?
      interactions = current_user.interactions_users
      hash = Gmaps4rails.build_markers(interactions) do |user, marker|
        marker.lat user.lat
        marker.lng user.long
      end
    end
    hash
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cobalt_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 2,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles:[{"featureType":"all","elementType":"all",
            "stylers":[{"invert_lightness":true},
               {"saturation":10},{"lightness":30},
               {"gamma":0.5},{"hue":"#435158"}]}]
  }
}, 
  function(){
    marker = handler.addMarker({
     lat: <%= current_user.lat %>,
     lng: <%= current_user.long %>,
     picture: {
       url: "http://i.imgur.com/vebhdRE.png?1",
       width: 60,
       height: 60
        },
     })
     handler.map.centerOn(marker)
     markers = handler.addMarkers(<%=raw hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
);

app/views/users/_default_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 3,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles: [{"featureType":"water", 
               "stylers":[{"color": "#021019"}]},
             {"featureType":"landscape",
               "stylers":[{"color":"#08304b"}]},
             {"featureType":"poi","elementType":"geometry",
               "stylers":[{"color":"#0c4152"}, {"lightness":5}]},
             {"featureType":"road.highway","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.highway","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b434f"}, {"lightness":25}]},
             {"featureType":"road.arterial","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.arterial","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b3d51"},{"lightness":16}]},
             {"featureType":"road.local","elementType":"geometry",
               "stylers":[{"color":"#000000"}]},
             {"elementType":"labels.text.fill", 
               "stylers":[{"color":"#ffffff"}]},
             {"elementType":"labels.text.stroke",
               "stylers":[{"color":"#000000"},{"lightness":13}]},
             {"featureType":"transit",
               "stylers":[{"color":"#146474"}]},
             {"featureType":"administrative","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"administrative","elementType":"geometry.stroke",
               "stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]}] 
  }
}, 
  function(){
     marker = handler.addMarker({
       lat: <%= current_user.lat %>,
       lng: <%= current_user.long %>,
       picture: {
         url: "http://i.imgur.com/vebhdRE.png?1",
         width: 60,
         height: 60
       },
     })
     handler.map.centerOn(marker)
     markers = handler.addMarkers(<%=raw hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
);

app/views/users/_hard_edges_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 2,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles: [{"featureType":"landscape.natural","stylers":[{"saturation":-100},{"lightness":100}]},{"featureType":"water","stylers":[{"saturation":-100},{"lightness":-86}]},{"elementType":"labels.text.stroke","stylers":[{"saturation":-100},{"lightness":100}]},{"featureType":"road","elementType":"geometry.stroke","stylers":[{"saturation":-100},{"lightness":-75}]},{"featureType":"road","elementType":"geometry.fill","stylers":[{"saturation":-100},{"lightness":97}]},{"featureType":"poi.park","stylers":[{"saturation":-100},{"lightness":-100}]},{"featureType":"poi.park","elementType":"labels.text.fill","stylers":[{"saturation":-100},{"lightness":100}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"landscape.man_made","stylers":[{"saturation":-100},{"lightness":-68}]},{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"saturation":-100},{"lightness":100}]},{"featureType":"administrative","elementType":"labels.text.stroke","stylers":[{"saturation":-100},{"lightness":-100}]},{"featureType":"poi","stylers":[{"saturation":-100},{"lightness":91}]},{"featureType":"poi","elementType":"labels.text.fill","stylers":[{"saturation":-100},{"lightness":-100}]},{"featureType":"transit.station","stylers":[{"saturation":-100},{"lightness":-22}]},{"featureType":"landscape.man_made","elementType":"geometry.stroke","stylers":[{"hue":"#ff004c"},{"saturation":-100},{"lightness":44}]},{"elementType":"labels.text.fill","stylers":[{"saturation":1},{"lightness":-100}]},{"elementType":"labels.text.stroke","stylers":[{"saturation":-100},{"lightness":100}]},{"featureType":"administrative.locality","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"administrative.locality","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"}]}]   
  }
}, 
  function(){
     marker = handler.addMarker({
       lat: <%= current_user.lat %>,
       lng: <%= current_user.long %>,
       picture: {
         url: "http://i.imgur.com/vebhdRE.png?1",
         width: 60,
         height: 60
       },
     })
     handler.map.centerOn(marker)
     markers = handler.addMarkers(<%=raw hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
);

app/views/users/_history.html.erb
<% unless journeys.empty? %>
  <% journeys.each do |j| %>
    <%= link_to raw("<div class='dash-knob'>
      <span class='white'>#{j.name.titleize}</span>
      <span id='interaction-count'>Interactions
      #{j.interactions.count}</span></div>"), 
      itenerary_path(j.itenerary) %>
  <% end %>
<% else %>
  <h3 class="white center-text">Sorry there were no results </h3>
  <h3 class="center-text"><%= link_to "start over", 
    users_search_journey_path(method: :get, search: ""),
    remote: true%></h1>
<% end %>

app/views/users/_itenerary_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 3,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles: [{"featureType":"water", 
               "stylers":[{"color": "#021019"}]},
             {"featureType":"landscape",
               "stylers":[{"color":"#08304b"}]},
             {"featureType":"poi","elementType":"geometry",
               "stylers":[{"color":"#0c4152"}, {"lightness":5}]},
             {"featureType":"road.highway","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.highway","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b434f"}, {"lightness":25}]},
             {"featureType":"road.arterial","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.arterial","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b3d51"},{"lightness":16}]},
             {"featureType":"road.local","elementType":"geometry",
               "stylers":[{"color":"#000000"}]},
             {"elementType":"labels.text.fill", 
               "stylers":[{"color":"#ffffff"}]},
             {"elementType":"labels.text.stroke",
               "stylers":[{"color":"#000000"},{"lightness":13}]},
             {"featureType":"transit",
               "stylers":[{"color":"#146474"}]},
             {"featureType":"administrative","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"administrative","elementType":"geometry.stroke",
               "stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]}] 
  }
}, 
  function(){
    marker = handler.addMarker({
       lat: <%= current_user.lat %>,
       lng: <%= current_user.long %>,
       picture: {
         url: "http://i.imgur.com/vebhdRE.png?1",
         width: 60,
         height: 60
       },
     })

     route = handler.addPolylines(
       <%= raw route %>,
       {strokeColor: '#efefef'});
     markers = handler.addMarkers(<%=raw hash.to_json %>);
     handler.bounds.extendWith(markers);
     handler.bounds.extendWith(polylines);

  }
);

app/views/users/_luner_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 2,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles:   [{"stylers":[{"hue":"#ff1a00"},
                           {"invert_lightness":true},
                           {"saturation":-100},
                           {"lightness":33},{"gamma":0.5}]},
                           {"featureType":"water","elementType":"geometry",
              "stylers":[{"color":"#2D333C"}]}]
  }
}, 
  function(){
    marker = handler.addMarker({
       lat: <%= current_user.lat %>,
       lng: <%= current_user.long %>,
       picture: {
         url: "http://i.imgur.com/vebhdRE.png?1",
         width: 60,
         height: 60
       },
     })

     markers = handler.addMarkers(<%=raw hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
)

app/views/users/_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 2,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles: [{"featureType":"water", 
               "stylers":[{"color": "#021019"}]},
             {"featureType":"landscape",
               "stylers":[{"color":"#08304b"}]},
             {"featureType":"poi","elementType":"geometry",
               "stylers":[{"color":"#0c4152"}, {"lightness":5}]},
             {"featureType":"road.highway","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.highway","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b434f"}, {"lightness":25}]},
             {"featureType":"road.arterial","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"road.arterial","elementType":"geometry.stroke",
               "stylers":[{"color":"#0b3d51"},{"lightness":16}]},
             {"featureType":"road.local","elementType":"geometry",
               "stylers":[{"color":"#000000"}]},
             {"elementType":"labels.text.fill", 
               "stylers":[{"color":"#ffffff"}]},
             {"elementType":"labels.text.stroke",
               "stylers":[{"color":"#000000"},{"lightness":13}]},
             {"featureType":"transit",
               "stylers":[{"color":"#146474"}]},
             {"featureType":"administrative","elementType":"geometry.fill",
               "stylers":[{"color":"#000000"}]},
             {"featureType":"administrative","elementType":"geometry.stroke",
               "stylers":[{"color":"#144b53"},{"lightness":14},{"weight":1.4}]}] 
  }
}, 
  function(){
     markers = handler.addMarkers(<%=raw @hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
);

app/views/users/_mock_graph.html.erb
<h4>circle graph to be built 
user will be the nuclius and his/her connections will form outer ring</h4>

app/views/users/_pale_dawn_map.html.erb
handler = Gmaps.build('Google');
handler.buildMap({ 
  internal: {id: 'map'},
  provider: {
    backgroundColor: "#021019",
    zoom: 2,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControl: false,
    zoomControlOptions: {position:google.maps.ControlPosition.BOTTOM_LEFT,
                         style:google.maps.ZoomControlStyle.SMALL 
                         },
    styles: [{"featureType":"water","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]},{"featureType":"landscape","stylers":[{"color":"#f2e5d4"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"administrative","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"road"},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{},{"featureType":"road","stylers":[{"lightness":20}]}]   
  }
}, 
  function(){
    marker = handler.addMarker({
       lat: <%= current_user.lat %>,
       lng: <%= current_user.long %>,
       picture: {
         url: "http://i.imgur.com/vebhdRE.png?1",
         width: 60,
         height: 60
       },
     })
     markers = handler.addMarkers(<%=raw hash.to_json %>)
     handler.bounds.extendWith(markers);
  }
);

app/views/users/dashboard.html.erb
<div class="hide" id="side-bar">
  <div id="close-dash-wrap">
    <span><%=link_to "X", "#", class: "on-top white", id: "close-side" %><span>
  </div>
  <div class="center-text" id="dash-controls">
    <ul>
      <h2 class="lobster">Dashboard</h2>
      <%= link_to raw( "<li class='dash-knob'>Take a Journey</li>"),
        "#", 
        class: "white",
        id: "side-bar-link" %>

      <% if current_user.profile %>
        <%= link_to raw( "<li class='dash-knob'>Profile</li>"),
          edit_profile_path(current_user.profile), 
          class: 'white' %>
      <% elsif %>
        <%= link_to raw( "<li class='dash-knob'>Create a Profile</li>"),
          "#", class: 'white', id: "new-profile" %>
      <% end %>

      <%= link_to raw( "<li class='dash-knob'>Map Options</li>"),
        "#", class: "white", id: "map-options" %>

      <%= link_to raw( "<li class='dash-knob'>History</li>"),
        users_history_path, class: "white" %>

      <%= link_to raw( "<li class='dash-knob'>Log Out</li>"),
        destroy_user_session_path, method: "delete", 
        class: 'white' %>
    </ul>
  </div>
  <div class="hide center-text" id="map-controls">
    <%= link_to "back to Dashboard", 
                "#", 
                class: "button small", 
                id: "back-dashboard"%>
    <h2 class="lobster">Map Options</h2>
    <div id="map-schemes">
      <%= link_to image_tag("luner_map.png"), 
      users_map_choice_path(map_choice: "luner_map"), 
        remote: true,
        id: "map-thumb",
        class: "th th-size" %>
      <%= link_to image_tag("cobalt_map.png"), 
        users_map_choice_path(map_choice: "cobalt_map"), 
        remote: true,
        id: "map-thumb",
        class: "th th-size" %>
      <%= link_to image_tag("hard_edges_map.png"), 
        users_map_choice_path(map_choice: "hard_edges_map"), 
        remote: true,
        id: "map-thumb",
        class: "th th-size" %>
      <%= link_to image_tag("pale_dawn_map.png"), 
        users_map_choice_path(map_choice: "pale_dawn_map"), 
        remote: true,
        id: "map-thumb",
        class: "th th-size" %>
       <%= link_to image_tag("default_map.png"), 
         users_map_choice_path(map_choice: "default_map"), 
         remote: true,
         id: "map-thumb",
         class: "th th-size" %>
    </div>
  </div>
</div>
<div class = "absolute">
  <%= link_to "Parents", guardians_for_parents_path, 
    class: "button small front", id: "for-parents-link" %>
  <%= link_to "Dashboard", "#", class: "button small front", id: "dashboard"%>
</div>
<div id="map-wrapper">
  <div id="map"></div>
</div>
<% unless current_user.profile%>
  <div class="show" id="modal-back"></div>
  <div class="show" id="modal">
    <div id="profile-wrapper">
      <div class="row">
        <div class="hide-for-small medium-12
          medium-centered large-8 large-centered columns">
            <%= image_tag "big-globe.png", id: "modal-globe" %>
        </div>
      </div>
      <div id="profileBox">
        <div class="row">
          <div class="small-8 small-centered medium-6
            medium-centered large-4 large-centered columns">
            <%= render partial: "/profiles/form" %>
            <%= link_to "I'll do this Later",
              "#",
              id: "close-modal",
              class: "button tiny secondary"%>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
<div class="hide" id="journey-modal">
  <div id="modal-back"></div>
  <div id="profile-wrapper">
    <div class="row">
      <div class="hide-for-small medium-12
        medium-centered large-8 large-centered columns">
          <%= image_tag "big-globe.png", id: "modal-globe" %>
      </div>
    </div>
    <div id="profileBox">
      <div class="row">
        <div class="small-8 small-centered medium-6
          medium-centered large-4 large-centered columns">
          <%= render "/journeys/journey_form" %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="map-space">
  <script>
    <%= render partial: @map, locals: {hash: @hash}  %>
  </script>
</div>

app/views/users/history.html.erb
<div class="dark-banner">
  <div class="dark-banner auto">
    <%= link_to "Parents", guardians_for_parents_path, class: "button small"%>
    <%= link_to "Dashboard", users_dashboard_path, class: "button small"%>
    <div class="row">
      <div class="large-12 center-text">
        <h1 class="lobster white">History</h1>
      </div>
      <div class="large-12 center-text">
        <%= form_tag users_search_journey_path, remote: true, method: :get  do %>
          <%= text_field_tag :search, nil, :placeholder => "search by name"%>
          <%= submit_tag "Search", class: "button"%>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 medium-12 large-12">
        <div id = "journey-search-results">
          <%= render partial: "history", locals: {journeys: @journeys}%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/map_choice.js.erb
$("#map-space").html("")
$("#map-space").append("<script><%= j render partial: @options_hash[:map_choice],
                       locals: {hash: @options_hash[:hash]} %></script>")

app/views/users/parent.html.erb
<div class="dark-banner-auto">
  <div class="dark-banner">
  <%= link_to "Dash", users_dashboard_path, class: "button small nav-link", 
    id: "dashboard-link" %>

    <div class="row">
      <div class="large-4 columns">
        <h1 class="white lobster">For Parents</h1>
      </div>
      <div class="large-8 columns">
        <%= link_to "Recent", guardians_recent_path, class: "button tiny"%>
        <%= link_to "Blocked", guardians_blocked_path, class: "button tiny"%>
        <%= link_to "Friends", guardians_friends_path, class: "button tiny"%>
        <%= link_to "Questions", guardians_questions_path, class: "button tiny"%>
        <%= link_to "Answers", guardians_answers_path, class: "button tiny"%>
      </div>
    </div>
    <div class = "row">
      <div class = "large-12 columns">
        <%= render partial: "guardians/log", 
          locals: {interactions: current_user.interactions}%>
      </div>
    </div>
  </div>
</div>

app/views/users/search_journey.js.erb
$("#journey-search-results").html("");
$("#journey-search-results").html("<%= j render partial: "history",
                                  locals: {journeys: @journeys}%>");