config/routes.rb
Sam::Application.routes.draw do

  get "welcome/index"
  get "interactions/symposium"
  get "itenerarys/choose_city"  
  get "users/map_choice"

  get "guardians/for_parents"
  get "guardians/recent"
  get "guardians/blocked"
  get "guardians/friends"
  get "guardians/questions"
  get "guardians/answers"

  devise_for :users
  devise_for :guardians, controllers: { registrations: "guardians/registrations" }

  resources :profiles
  resources :journeys
  resources :itenerarys

  get "users/dashboard"
  get "users/history"
  get "users/search_journey"

  root 'welcome#index'

end

app/models/itenerary.rb
class Itenerary < ActiveRecord::Base

  include Photo
  include Wiki
  include Weather

  belongs_to :journey
  has_many :interactions
  has_many :users, through: :interactions, dependent: :destroy

  validates :journey_id, presence: true

  def user
    journey = self.journey
    journey.user
  end

  def users
    array = []
    self.interactions.each do |inter|
      array << inter.user
    end
    array
  end

  def cities
    array = []
    self.users.each do |user|
      array << user.city
    end
    array
  end

  def photos array
    search = Photo::Search.new array
    search.image_urls
  end

  def interaction_photos
    photos self.cities
  end

  def city_info city
    Wiki::Willy.new(city.to_s).summary
  end

  def city_weather city
    weather = Weather::Forcast.new(city)
    {temp: weather.temp, overview: weather.overview}
  end

  def route
    array = [{lat: self.user.lat, lng: self.user.long}]
    Interaction.users(self.interactions).each do |user|
      array << {lat: user.lat, lng: user.long}
    end
    [array].to_json
  end

end

app/controllers/itenerarys_controller.rb
class ItenerarysController < ApplicationController

  respond_to :js, :html

  def show
    user = current_user
    @itenerary = Itenerary.find(params[:id])
    @journey = @itenerary.journey
    @interactions = @itenerary.interactions

    array = []
    @interactions.each do |inter|
      array << inter.user
    end
    @destinations = array.map {|user| user.city }

    @city = @destinations.first
    @city_info = @itenerary.city_info(@city)
    @weather = @itenerary.city_weather(@city)

    #a hash for the Gmap markers
    @hash = gmap @interactions
    @route = @itenerary.route
    @map = "default_map"

    @photos = @itenerary.interaction_photos
    @base = user.distance_to_increment(user.city, @destinations.first)
    @distance = user.city_distance @destinations
    @total_distance = total_distance
  end

  def choose_city
    @itenerary = Itenerary.find(params[:id])
    @photos = @itenerary.interaction_photos 
    city = params[:city]
    city_info = @itenerary.city_info(city)
    weather = @itenerary.city_weather(city)
    @respond = {photos: @photos, 
                full_image: @photos[city].first,
                city: city,
                weather: weather,
                city_info: city_info}
    respond_with @respond
  end

  def gmap interactions
    #the map requires a partial with the style of map 
    #and a markers hash for desired pins
    Gmaps4rails.build_markers(Interaction.users(interactions)) do |user, marker|
      marker.lat user.lat
      marker.lng user.long
    end
  end

  def city
    unless params[:city]
      @city = @destinations.first
    else
      @city = params[:city]
    end
  end

  def total_distance 
    distance = 0
    @distance.each {|k, v| distance += v } 
    distance + @base
  end

  def update
  end

  def create
  end

  def destroy
    itenerary = Itenerary.find(params[:id])
    itenerary.destroy
    redirect_to users_dashboard_path
  end

end

app/helpers/itenerary_helper.rb
module IteneraryHelper
end

app/views/itenerarys/_photo_wall.html.erb
<div id="photos-wrapper">
 <% photos[city].each do |photo|%>
   <a>
     <%= image_tag photo, class: "city-img-th th", id: "city-image", alt: city%>
   </a>
 <% end %>
</div>

app/views/itenerarys/choose_city.js.erb
$("#photo-wall").html("");
$("#photo-wall").html("<%= j render partial: "photo_wall",
                      locals: {photos: @respond[:photos], city: @respond[:city]}%>");
function complete(){
  $("#wiki").html("");
  $("#wiki").html("<%= j @respond[:city_info] %>");
  $("#overview").html("<%= j @respond[:weather][:overview]%>")
  $("#temp").html("<%= @respond[:weather][:temp] %>° Celsius")
  $("#full-image").attr("src", "<%= j @respond[:full_image] %>");
  $("#city-title").html("<%= j @respond[:city]%>")
  $("#profile-wrapper").fadeIn('slow')
};
$("#profile-wrapper").fadeOut( complete )

app/views/itenerarys/create.html.erb
<h1>Itenerary#create</h1>
<p>Find me in app/views/itenerary/create.html.erb</p>

app/views/itenerarys/destroy.html.erb
<h1>Itenerary#destroy</h1>
<p>Find me in app/views/itenerary/destroy.html.erb</p>

app/views/itenerarys/show.html.erb
<div class = "dark-banner auto">
<!-- #scaleable side bar --!>
  <div class = "small-2 medium-2 large-1" id="photo-wall" >
    <%= render partial: "photo_wall", locals: {photos: @photos, city: @city}%>
  </div>
  <%= link_to "Parents", guardians_for_parents_path, 
    class: "button small nav-link", id: "for-parents-link" %>
  <%= link_to "Dash", users_dashboard_path, class: "button small nav-link", 
    id: "dashboard-link" %>
  <%= link_to "Map", "#",
    class: "button small nav-link", 
    id: "map-link" %> 
  <span class="hide" id="close-map-wrap">
    <%= link_to "X", "#",
      class: "button small nav-link", 
      id: "close-map-link" %> 
  </span>

 <div id="blur-wrapper">
 </div>

  <div id="map-wrapper">
    <div id="grayscale-wrapper">
      <div id="map"></div>
    </div>
  </div>

  <div class="row">
    <div class="small-8 medium-6 large-centered large-6 columns">
      <div id="content-wrapper">
        <h2 class="lobster white">Itenerary</h2>
        <div class="show" id="trip-details">
          <h6 class="white">Total Distance: <%= @total_distance%> m.</h6>
          <h6 class="white">Destinations: <%= @destinations.count%></h6>
          <%= link_to "Start Journey", 
            interactions_symposium_path(id: @itenerary.id), 
            class: "button small success", id: "go"%>
          <%= link_to "Cancel", journey_path(@journey),
            method: :delete,
            class: "small button alert", id: "go"%>
        </div>
        <div class="show" id="city-list">
          <div class='dash-knob white center-text'>
            <%= current_user.city %><%= image_tag "http://imgur.com/vebhdRE.png?1"%>
          </div>
          <div class="center-text"id="miles-circle">
            <span id="miles"><%= @base %> m.</span>
          </div>
          <% @destinations.each do |city|%>
          <%= link_to  raw("<div class='dash-knob white center-text'>
                    #{city}</div>"),
              itenerarys_choose_city_path(city: city, id: @itenerary.id),
              remote: true %>
            <% unless city == @destinations.last%>
              <div class="center-text" id= "miles-circle">
                <span id="miles"><%= @distance[city]%> m.</span>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <!-- modal for images --!>
  <div class="hide" id="image-modal">
    <div id="modal-back-img"></div>
    <div id="profile-wrapper">
      <div id= "title-info-box" class="center-text right">
        <h2 id="city-title" class="lobster"></h2>
        <h4><%= link_to "Info", "#", 
             class: "center-text", id: "info-link"%>
             |
             <%= link_to image_tag("http://i.imgur.com/0D9TeuG.png?1"), "#", 
             class: "center-text", id: "weather-link"%></h4>
      </div>
      <div id="img-modal-nav">
        <%= link_to "X", "#", class: "button tiny", 
           id: "close-image-modal" %>
        <ul>
          <% @destinations.each do |city| %>
             <li class="white", id: "image-description">
               <%= link_to city, itenerarys_choose_city_path(city: city,
                                 id: @itenerary.id), 
                                 remote: true,
                                 class: "city-list",
                                 id: city %>
             </li> 
          <% end %>
         </ul>
      </div>
      <div id="profileBox">
        <div class="row">
          <div class="small-10 medium-centered medium-6 large-6 columns">
            <img class = "hide" id = "full-image" src = "" >
          </div>
        </div>
        <div class="row">
          <div class="small-11 medium-centered medium-6 large-10 columns">
            <div class="hide" id = "weather-wrapper">
              <h2 class="lobster grey" 
                  id="overview"><%="#{@weather[:overview]}"%></h2>
              <h5 class="grey" id="temp"><%="#{@weather[:temp]}° Celsius"%></h5>
            </div>
          </div>
          <div class="small-11 medium-centered medium-6 large-10 columns">
            <h5 class="grey hide" id="wiki"><%= @city_info %></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  <%= render partial: "/users/itenerary_map", 
             locals: {hash: @hash, route: @route}%>
</script>

app/views/itenerarys/update.html.erb
<h1>Itenerary#update</h1>
<p>Find me in app/views/itenerary/update.html.erb</p>