config/routes.rb
Sam::Application.routes.draw do

  get "welcome/index"
  get "interactions/symposium"
  get "itenerarys/choose_city"  
  get "users/map_choice"

  get "guardians/for_parents"
  get "guardians/recent"
  get "guardians/blocked"
  get "guardians/friends"
  get "guardians/questions"
  get "guardians/answers"

  devise_for :users
  devise_for :guardians, controllers: { registrations: "guardians/registrations" }

  resources :profiles
  resources :journeys
  resources :itenerarys

  get "users/dashboard"
  get "users/history"
  get "users/search_journey"

  root 'welcome#index'

end

app/models/journey.rb
class Journey < ActiveRecord::Base

  include Shaman

  belongs_to :user
  has_one :itenerary, dependent: :destroy

  validates :name, :user_id, :distance,  presence: true
  validates :user_id, uniqueness: { scope: :name }

  after_save :begin_journey

  def begin_journey
    journey =  Shaman::Journey.new journey: self
    journey.create_itenerary
  end

  def short?
    self.distance == "short"
  end

  def long?
    self.distance == "long"
  end

  def interactions
    self.itenerary.interactions
  end

  def self.search query, id
    ::Journey.where("name LIKE ? AND user_id = ?", "%#{query}%", "#{id}")
  end

end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController

  respond_to :js, :html

  def create
    journey = Journey.new(name: params[:name], 
                             distance: params[:distance],
                             user_id: current_user.id)
    if journey.save
      itenerary = journey.itenerary
      redirect_to itenerary_path(itenerary) 
    end
  end

  def destroy
    journey = Journey.find(params[:id])
    journey.destroy
    redirect_to users_dashboard_path
  end
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/views/journeys/_journey_form.html.erb
<%= form_tag journeys_path, method: :post do %> 
  <h1 class= "white lobster">Time to Travel</h1>
  <h4 class="white">Name your Journey</h4>
  <%= text_field_tag :name, nil, placeholder: "My first Journey"%>
  <%= radio_button_tag(:distance, "short")%>
  <%= label_tag :distance, "short", class: "white"%>
  <%= radio_button_tag(:distance, "long" )%>
  <%= label_tag :distance, "long", class: "white" %> </br>
  <%= submit_tag "Start your Journey", class: "button"%>
  <%= link_to "I'll do this later",
              "#",
              id: "close-modal",
              class: "button tiny secondary"%>
<% end %>

app/views/journeys/create.html.erb
<h1>Journeys#create</h1>
<p>Find me in app/views/journeys/create.html.erb</p>

app/views/journeys/destroy.html.erb
<h1>Journeys#destroy</h1>
<p>Find me in app/views/journeys/destroy.html.erb</p>